In [3]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])

print(x)

x.shape

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])
print(y)

tensor([[0.7345, 0.2723, 0.7813, 0.1674, 0.9846],
        [0.2439, 0.9573, 0.9917, 0.5716, 0.5636]])


In [ ]:
#flatten operation
y.view([1,10])